data_generating_process: dgp1_stabilized_weight

augmentation_params:
  function: augment_stabilized_weights
  kwargs:
    method: quantile
    n_quantiles: 100

# Model parameters
kde:
  model: kde
  stabilized_weight: True

kliep:
  model: kernel
  method: KLIEP
  basis_dimensions: [100, 200, 500]
  bandwidths: [1.0, 2.0, 5.0, 10.0]
  num_iterations: 5000

ulsif:
  model: kernel
  method: uLSIF
  basis_dimensions: [100, 200, 500]
  bandwidths: [1.0, 2.0, 5.0, 10.0]
  smoothing_parameters: [0.0, 0.1, 0.5, 1.0]

lsif:
  model: kernel
  method: LSIF
  # current implementation does not support cross validation
  basis_dimensions: [500]
  bandwidths: [10.0]
  smoothing_parameters: [0.0]

nnet:
  model: nnet
  objective: ["least_squares", "kullback_leibler", "cross_entropy"]
  depth: 2
  width: 20
  learning_rate: 1.0e-4
  num_iterations: 1000
  early_stopping_round: 5
  batch_size: 125

booster:
  model: lgb
  objective: ["least_squares", "kullback_leibler", "cross_entropy"]
  max_leaves: 20
  learning_rate: 1.0e-3
  num_iterations: 1000
  force_col_wise: True
  early_stopping_round: 10
